"""
Report Generator Service — PDF + Excel
Plug-and-play module. Does NOT modify any existing service or route.
Uses reportlab.platypus for structured PDF and openpyxl for Excel.
"""

from io import BytesIO
from datetime import datetime, timezone
from collections import Counter


# ──────────────────────────────────────────────────────────
# PDF Generation
# ──────────────────────────────────────────────────────────

def generate_pdf_report(
    title: str,
    generated_by: str,
    kpis: dict,
    category_dist: dict,
    status_dist: dict,
    priority_dist: dict,
    complaints: list,
    filters: dict,
) -> bytes:
    """Generate a structured PDF report with KPIs, charts-as-tables, and raw data."""
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        PageBreak, HRFlowable
    )

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=20 * mm, bottomMargin=20 * mm,
        title=title,
        author="JanSamadhan System"
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"],
        fontSize=22, textColor=colors.HexColor("#1e3a8a"),
        spaceAfter=6
    )
    subtitle_style = ParagraphStyle(
        "ReportSubtitle", parent=styles["Normal"],
        fontSize=10, textColor=colors.grey, spaceAfter=16
    )
    section_style = ParagraphStyle(
        "SectionHead", parent=styles["Heading2"],
        fontSize=14, textColor=colors.HexColor("#1e40af"),
        spaceBefore=18, spaceAfter=8
    )
    normal = styles["Normal"]

    elements = []

    # ── Header ──
    elements.append(Paragraph(title, title_style))
    now = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
    filter_str = ", ".join(
        f"{k}: {v}" for k, v in filters.items() if v
    ) or "None"
    elements.append(Paragraph(
        f"Generated by: {generated_by} | Date: {now} | Filters: {filter_str}",
        subtitle_style
    ))
    elements.append(HRFlowable(width="100%", color=colors.HexColor("#cbd5e1")))
    elements.append(Spacer(1, 10))

    # ── KPI Summary Table ──
    elements.append(Paragraph("Key Performance Indicators", section_style))
    kpi_data = [["Metric", "Value"]]
    kpi_data.append(["Total Complaints", str(kpis.get("total", 0))])
    kpi_data.append(["Resolved", str(kpis.get("resolved", 0))])
    kpi_data.append(["Pending", str(kpis.get("pending", 0))])
    kpi_data.append(["Resolution Rate", f"{kpis.get('resolution_rate', 0):.1f}%"])
    kpi_data.append(["Emergency Cases", str(kpis.get("emergency", 0))])
    kpi_data.append(["Avg Satisfaction", f"{kpis.get('avg_satisfaction', 0):.1f} / 5"])

    kpi_table = Table(kpi_data, colWidths=[200, 200])
    kpi_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e40af")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 11),
        ("FONTSIZE", (0, 1), (-1, -1), 10),
        ("ALIGN", (1, 0), (1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(kpi_table)
    elements.append(Spacer(1, 14))

    # ── Category Distribution ──
    if category_dist:
        elements.append(Paragraph("Category Distribution", section_style))
        cat_data = [["Category", "Count", "Percentage"]]
        total = sum(category_dist.values()) or 1
        for cat, count in sorted(category_dist.items(), key=lambda x: -x[1]):
            cat_data.append([cat, str(count), f"{count / total * 100:.1f}%"])
        cat_table = Table(cat_data, colWidths=[200, 100, 100])
        cat_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f766e")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0fdfa")]),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        elements.append(cat_table)
        elements.append(Spacer(1, 14))

    # ── Status Distribution ──
    if status_dist:
        elements.append(Paragraph("Status Distribution", section_style))
        stat_data = [["Status", "Count"]]
        for s, c in sorted(status_dist.items(), key=lambda x: -x[1]):
            stat_data.append([s.replace("_", " ").title(), str(c)])
        stat_table = Table(stat_data, colWidths=[200, 100])
        stat_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#7c3aed")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#faf5ff")]),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        elements.append(stat_table)
        elements.append(Spacer(1, 14))

    # ── Priority Distribution ──
    if priority_dist:
        elements.append(Paragraph("Priority Distribution", section_style))
        prio_data = [["Priority", "Count"]]
        for p, c in sorted(priority_dist.items(), key=lambda x: -x[1]):
            prio_data.append([p.title(), str(c)])
        prio_table = Table(prio_data, colWidths=[200, 100])
        prio_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#dc2626")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#fef2f2")]),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        elements.append(prio_table)

    # ── Raw Data Table (Page Break) ──
    if complaints:
        elements.append(PageBreak())
        elements.append(Paragraph(f"Grievance Records ({len(complaints)} entries)", section_style))
        headers = ["ID", "Title", "Category", "Status", "Priority", "Region", "Filed On"]
        raw_data = [headers]
        for c in complaints[:200]:  # Cap at 200 rows for PDF
            raw_data.append([
                str(c.get("grievanceID", c.get("id", "")))[:16],
                str(c.get("title", ""))[:30],
                str(c.get("category", "")),
                str(c.get("status", "")).replace("_", " ").title(),
                str(c.get("priority", "")).title(),
                str(c.get("region", "")),
                str(c.get("createdAt", ""))[:10],
            ])
        raw_table = Table(raw_data, colWidths=[70, 110, 70, 60, 55, 60, 60], repeatRows=1)
        raw_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#334155")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 7),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#e2e8f0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        elements.append(raw_table)

    # ── Footer note ──
    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        "This report was auto-generated by JanSamadhan. Data is accurate as of the generation timestamp.",
        ParagraphStyle("Footer", parent=normal, fontSize=8, textColor=colors.grey)
    ))

    doc.build(elements)
    return buffer.getvalue()


# ──────────────────────────────────────────────────────────
# Excel Generation
# ──────────────────────────────────────────────────────────

def generate_excel_report(
    title: str,
    generated_by: str,
    kpis: dict,
    category_dist: dict,
    status_dist: dict,
    priority_dist: dict,
    complaints: list,
    filters: dict,
) -> bytes:
    """Generate a multi-sheet Excel workbook with Summary + Raw Data."""
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

    wb = Workbook()

    # ── Styles ──
    header_font = Font(bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill(start_color="1E40AF", end_color="1E40AF", fill_type="solid")
    section_font = Font(bold=True, color="1E3A8A", size=12)
    thin_border = Border(
        left=Side(style="thin", color="E2E8F0"),
        right=Side(style="thin", color="E2E8F0"),
        top=Side(style="thin", color="E2E8F0"),
        bottom=Side(style="thin", color="E2E8F0"),
    )

    # ── Sheet 1: Summary ──
    ws = wb.active
    ws.title = "Summary"
    ws.sheet_properties.tabColor = "1E40AF"

    row = 1
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=3)
    cell = ws.cell(row=row, column=1, value=title)
    cell.font = Font(bold=True, size=16, color="1E3A8A")
    row += 1
    now = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
    ws.cell(row=row, column=1, value=f"Generated by: {generated_by} | {now}")
    ws.cell(row=row, column=1).font = Font(size=9, color="94A3B8")
    row += 2

    # KPIs
    ws.cell(row=row, column=1, value="Key Performance Indicators").font = section_font
    row += 1
    kpi_items = [
        ("Total Complaints", kpis.get("total", 0)),
        ("Resolved", kpis.get("resolved", 0)),
        ("Pending", kpis.get("pending", 0)),
        ("Resolution Rate", f"{kpis.get('resolution_rate', 0):.1f}%"),
        ("Emergency Cases", kpis.get("emergency", 0)),
        ("Avg Satisfaction", f"{kpis.get('avg_satisfaction', 0):.1f} / 5"),
    ]
    for label, value in kpi_items:
        ws.cell(row=row, column=1, value=label).font = Font(bold=True)
        ws.cell(row=row, column=2, value=str(value))
        for col in range(1, 3):
            ws.cell(row=row, column=col).border = thin_border
        row += 1
    row += 1

    # Category Distribution
    if category_dist:
        ws.cell(row=row, column=1, value="Category Distribution").font = section_font
        row += 1
        for h_col, h_val in enumerate(["Category", "Count", "Percentage"], 1):
            c = ws.cell(row=row, column=h_col, value=h_val)
            c.font = header_font
            c.fill = PatternFill(start_color="0F766E", end_color="0F766E", fill_type="solid")
        row += 1
        total = sum(category_dist.values()) or 1
        for cat, count in sorted(category_dist.items(), key=lambda x: -x[1]):
            ws.cell(row=row, column=1, value=cat)
            ws.cell(row=row, column=2, value=count)
            ws.cell(row=row, column=3, value=f"{count / total * 100:.1f}%")
            for col in range(1, 4):
                ws.cell(row=row, column=col).border = thin_border
            row += 1
        row += 1

    # Status Distribution
    if status_dist:
        ws.cell(row=row, column=1, value="Status Distribution").font = section_font
        row += 1
        for h_col, h_val in enumerate(["Status", "Count"], 1):
            c = ws.cell(row=row, column=h_col, value=h_val)
            c.font = header_font
            c.fill = PatternFill(start_color="7C3AED", end_color="7C3AED", fill_type="solid")
        row += 1
        for s, cnt in sorted(status_dist.items(), key=lambda x: -x[1]):
            ws.cell(row=row, column=1, value=s.replace("_", " ").title())
            ws.cell(row=row, column=2, value=cnt)
            for col in range(1, 3):
                ws.cell(row=row, column=col).border = thin_border
            row += 1
        row += 1

    # Priority Distribution
    if priority_dist:
        ws.cell(row=row, column=1, value="Priority Distribution").font = section_font
        row += 1
        for h_col, h_val in enumerate(["Priority", "Count"], 1):
            c = ws.cell(row=row, column=h_col, value=h_val)
            c.font = header_font
            c.fill = PatternFill(start_color="DC2626", end_color="DC2626", fill_type="solid")
        row += 1
        for p, cnt in sorted(priority_dist.items(), key=lambda x: -x[1]):
            ws.cell(row=row, column=1, value=p.title())
            ws.cell(row=row, column=2, value=cnt)
            for col in range(1, 3):
                ws.cell(row=row, column=col).border = thin_border
            row += 1

    # Auto-width columns
    for col_cells in ws.columns:
        max_len = 0
        col_letter = col_cells[0].column_letter
        for cell in col_cells:
            if cell.value:
                max_len = max(max_len, len(str(cell.value)))
        ws.column_dimensions[col_letter].width = min(max_len + 4, 40)

    # ── Sheet 2: Raw Data ──
    ws2 = wb.create_sheet("Raw Data")
    ws2.sheet_properties.tabColor = "334155"

    raw_headers = [
        "Grievance ID", "Title", "Description", "Category", "Status",
        "Priority", "Region", "Location", "Filed By", "Filed On",
        "Assigned Officer", "Votes"
    ]
    for col, h in enumerate(raw_headers, 1):
        c = ws2.cell(row=1, column=col, value=h)
        c.font = header_font
        c.fill = header_fill
        c.alignment = Alignment(horizontal="center")

    for r_idx, comp in enumerate(complaints, 2):
        ws2.cell(row=r_idx, column=1, value=str(comp.get("grievanceID", comp.get("id", ""))))
        ws2.cell(row=r_idx, column=2, value=str(comp.get("title", "")))
        ws2.cell(row=r_idx, column=3, value=str(comp.get("description", ""))[:200])
        ws2.cell(row=r_idx, column=4, value=str(comp.get("category", "")))
        ws2.cell(row=r_idx, column=5, value=str(comp.get("status", "")).replace("_", " ").title())
        ws2.cell(row=r_idx, column=6, value=str(comp.get("priority", "")).title())
        ws2.cell(row=r_idx, column=7, value=str(comp.get("region", "")))
        ws2.cell(row=r_idx, column=8, value=str(comp.get("location", "")))
        ws2.cell(row=r_idx, column=9, value=str(comp.get("name", comp.get("citizen_email", ""))))
        ws2.cell(row=r_idx, column=10, value=str(comp.get("createdAt", ""))[:19])
        ws2.cell(row=r_idx, column=11, value=str(comp.get("assigned_officer", "") or "Unassigned"))
        ws2.cell(row=r_idx, column=12, value=comp.get("votes", 0))
        for col in range(1, len(raw_headers) + 1):
            ws2.cell(row=r_idx, column=col).border = thin_border

    # Auto-width
    for col_cells in ws2.columns:
        max_len = 0
        col_letter = col_cells[0].column_letter
        for cell in col_cells:
            if cell.value:
                max_len = max(max_len, len(str(cell.value)))
        ws2.column_dimensions[col_letter].width = min(max_len + 3, 50)

    # Freeze header row
    ws2.freeze_panes = "A2"
    ws2.auto_filter.ref = ws2.dimensions

    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()


# ──────────────────────────────────────────────────────────
# Helper: compute distributions from complaint list
# ──────────────────────────────────────────────────────────

def compute_distributions(complaints: list) -> dict:
    """Compute category, status, and priority distributions from a list of complaints."""
    category_dist = Counter(c.get("category", "Other") for c in complaints)
    status_dist = Counter((c.get("status") or "submitted").lower() for c in complaints)
    priority_dist = Counter((c.get("priority") or "medium").lower() for c in complaints)

    total = len(complaints)
    resolved = sum(1 for c in complaints if (c.get("status") or "").lower() in {"resolved", "closed"})
    pending = total - resolved
    emergency = sum(1 for c in complaints if (c.get("priority") or "").lower() == "emergency")

    # Average satisfaction
    all_ratings = []
    for c in complaints:
        fb = c.get("feedback", [])
        if isinstance(fb, list):
            for f in fb:
                if isinstance(f, dict) and f.get("rating"):
                    all_ratings.append(f["rating"])
    avg_sat = sum(all_ratings) / len(all_ratings) if all_ratings else 0

    kpis = {
        "total": total,
        "resolved": resolved,
        "pending": pending,
        "resolution_rate": (resolved / total * 100) if total else 0,
        "emergency": emergency,
        "avg_satisfaction": avg_sat,
    }

    return {
        "kpis": kpis,
        "category_dist": dict(category_dist),
        "status_dist": dict(status_dist),
        "priority_dist": dict(priority_dist),
    }
