from fastapi import APIRouter, Depends, BackgroundTasks, HTTPException
from pydantic import BaseModel
import time
from config import settings
from dependencies import get_current_user
import logging

logger = logging.getLogger(__name__)

router = APIRouter()

class TestEmailRequest(BaseModel):
    email: str
    subject: str = "Test Email from JanSamadhan"

@router.post("/test-email")
async def test_email(request: TestEmailRequest, user: dict = Depends(get_current_user)):
    """
    Diagnostic endpoint to send a test Email synchronously to verify SMTP configuration.
    """
    if user.get("role") != "admin":
        raise HTTPException(status_code=403, detail="Admin access required")

    logger.info(f"[DIAGNOSTICS] Triggering test email to {request.email}")
    
    from services.email_service import email_service
    
    context = {
        "content": "This is a diagnostic test email generated by the JanSamadhan Notification System to verify SMTP settings.",
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S")
    }
    
    result = await email_service.send_email(
        to_email=request.email,
        subject=request.subject,
        template_name="base",
        context=context,
        max_retries=1
    )
    
    if result.get("success"):
        return {
            "success": True,
            "message": "Test Email sent successfully.",
            "diagnostics": result
        }
    else:
        return {
            "success": False,
            "message": "Test Email failed to send.",
            "diagnostics": result
        }
